export const MEETUP_SUBSCRIBE_REQUEST = '@meetup/SUBSCRIBE_REQUEST';
export const MEETUP_SUBSCRIBE_SUCCESS = '@meetup/SUBSCRIBE_SUCCESS';
export const MEETUP_SUBSCRIBE_FAILURE = '@meetup/SUBSCRIBE_FAILURE';
export const MEETUP_UNSUBSCRIBE_REQUEST = '@meetup/UNSUBSCRIBE_REQUEST';
export const MEETUP_UNSUBSCRIBE_SUCCESS = '@meetup/UNSUBSCRIBE_SUCCESS';
export const MEETUP_UNSUBSCRIBE_FAILURE = '@meetup/UNSUBSCRIBE_FAILURE';
