export const MEETUP_SUBSCRIBE_REQUEST = '@meetup/SUBSCRIBE_REQUEST';
export const MEETUP_SUBSCRIBE_SUCCESS = '@meetup/SUBSCRIBE_SUCCESS';
export const MEETUP_SUBSCRIBE_FAILURE = '@meetup/SUBSCRIBE_FAILURE';
